### ISSUE TITLE
Add Raspbian support to get-dess.sh

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/dess#10]
Once we have @XavierChanth excellent work with #8 merged...

**Describe the solution you'd like**
Allow dess to be installed on a Raspberry Pi with its most common distro in the same way as it works on cloud VMs etc.

**Describe alternatives you've considered**
Pi users could use Ubuntu etc.

**Additional context**
We may need to create an Armv7 image for atsigncompany/secondary:dess, which can't be automated due to the [issues with Dart on Armv7 in QEMU](https://github.com/dart-lang/dart-docker/issues/11#issuecomment-867407449)

@cconstab can get a cloudy Pi on Mythic Beasts for testing.

**Comment by xavierchanth** [comment]
Was able to install all required dependencies for dess.
After testing, it appears we will need an Armv7 image.

**Comment by cpswan** [comment]
We have an issue open for that with [at_server#168](https://github.com/atsign-foundation/at_server/issues/168)

**Comment by cpswan** [comment]
@XavierChanth if you can get one of the cloudy pis set up to do the Docker build then I'll work on incorporating that into the at_server automation.

**Comment by xavierchanth** [comment]
> @XavierChanth if you can get one of the cloudy pis set up to do the Docker build then I'll work on incorporating that into the at_server automation.

Sounds good, @cpswan am I meant to setup and verify that one of the pis is able to run ```build_push.sh``` from  [at_server#168](https://github.com/atsign-foundation/at_server/issues/168)?

**Comment by cpswan** [comment]
It just needs to be able to build the Dockerfile at https://github.com/atsign-foundation/at_server/blob/trunk/at_secondary/Dockerfile

**Comment by cpswan** [comment]
@XavierChanth the atsigncompany/secondary:dess is now available for armv7 (and automation for future builds is in place).

**Comment by xavierchanth** [comment]
I just tested the image, looks good on Raspbian 10. I will submit a PR shortly.
