### ISSUE TITLE
Scripts should exit when an error occurs

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/dess#20]
**Describe the bug**
At present the dess-create script will plough on to producing a QR code (taking up an entire standard terminal window) even if steps haven't completed successfully

**To Reproduce**
My particular source of error wouldn't happen with the latest scripts, but there will be other errors

**Expected behavior**
Script should exit, as the display of a QR code suggests all is well, and pushes any error messages out of view.

**Comment by xavierchanth** [comment]
I've added the exit on error checks for all network & docker related tasks in create.sh
