### ISSUE TITLE
ReadMe.md -- Add current build/workflow status and license badge 

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/dess#22]
A status badge shows whether a workflow is currently failing or passing. In addition	to this, it is important to show our Github BSD 3-clause License badge on all public repositories.

A common place to add the status and license badge is in the ```README.md``` at the top alongside the GitHub License.

```diff
+ ![example workflow](https://github.com/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg)
+ [![GitHub License](https://img.shields.io/badge/license-BSD3-blue.svg)](./LICENSE)
```

**Comment by sdesani** [comment]
I was playing around with this one, but does not seem this repo has any actions set up yet. Is that something that will get added on different issue ?

**Comment by cpswan** [comment]
@sdesani this one just needs a license badge for now.

**Comment by sdesani** [comment]
Sounds good. Updated the ReadMe and created the PR - https://github.com/atsign-foundation/dess/pull/24
Can you assign this issue to me and review the PR whenever you get a chance ?
