### ISSUE TITLE
get.docker.io style single piece script

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/dess#6]
**Describe the solution you'd like**
A single script that can be `curl`ed and run in a shell that evaluates the platform it finds itself in (e.g. Ubuntu/Debian or Fedora/CentOS) and runs commands appropriate to the package manager.

**Describe alternatives you've considered**
Standalone scripts for apt/dpkg vs yum/rpm

**Additional context**
[rustup.rs](https://rustup.rs/) is another good example
Source for get.docker is at [docker/docker-install](https://github.com/docker/docker-install) NB use of ShellCheck :)

**Comment by xavierchanth** [comment]
I've added a function to the install_software.sh file that will clone the repository if it is missing. Will this suffice?

**Comment by xavierchanth** [comment]
This should allow the install_software.sh file to be curled and run on its own.

**Comment by cpswan** [comment]
My preference would be to not need git (the client) at all.

The script could copy assets from GitHub, but bootstrapping using the git client as we do now shouldn't be necessary.

**Comment by xavierchanth** [comment]
Okay, my PR is already looking quite lengthy, I can look into stripping out the git requirement in a later PR.

**Comment by cpswan** [comment]
Lots of progress on this with #8 

Now just need to move a gh_pages branch hosting get_dess.sh with a prettier URL e.g. getdess.atsign.com

**Comment by cpswan** [comment]
I went with a redirect to the existing script location.

@sherif8532 provided #11 to update docs (after we weren't able to merge his good work on #7 due to conflicts with #8)
