### ISSUE TITLE
Update docs to latest terminology (mostly s/@/at/

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/dess#84]
### Is your feature request related to a problem? Please describe.

The instructions were last updated a couple of years ago, so they're still littered with `@sign` rather than `atSign` and `secondary` rather than `atServer` etc.

### Describe the solution you'd like

Replace `@` with `at` where appropriate

**Comment by Areadrill** [comment]
Hey. Can I be assigned to this please?
