### ISSUE TITLE
atsign.dev 2.0 : Need content, diagrams, samples and examples for Dess

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/dess#9]
For this link on the dev site need content that can be ported.

https://devstaging.atsign.wtf/docs/functional_architecture/dess/

**Comment by xavierchanth** [comment]
Moved the content to https://devstaging.atsign.wtf/docs/get-started/dess.
Step by step documentation/examples have been moved under guides/dess-setup.

**Comment by xavierchanth** [comment]
Is it safe to close this issue @anthonyvprakash?
